permissions:
  contents: write

name: update-deals

on:
  schedule:
    - cron: '0 * * * *'        # runs at the top of every hour
  workflow_dispatch:          # allows manual trigger

jobs:
  fetch-deals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

     	with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch new deals
        run: node deals.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PARTNER_TAG: ${{ secrets.PARTNER_TAG }}

      - name: Commit & push updated deals.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deals.json
          git commit -m "chore: update deals"
          git push
