
name: Daily Amazon Deals Scrape

permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *'       # every day at 2 AM UTC
  workflow_dispatch:         # allow manual runs

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Check out with write perms
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 2️⃣ Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install scraper deps
      - name: Install scraping libs
        run: pip install requests beautifulsoup4

      # 4️⃣ Run your scraper
      - name: Fetch deals via scraper
        run: python fetch_deals.py
        env:
          PAAPI_PARTNER_TAG: ${{ secrets.PAAPI_PARTNER_TAG }}

      # 5️⃣ Auto-commit any changes to deals.json
      - name: Commit updated deals.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔄 Daily scrape update"
          file_pattern: deals.json
          branch: main
